gateway: bump minio dep to resolve upstream spurious warnings
this makes

  API: SYSTEM()
  Time: 16:09:36 MST 11/13/2020
  DeploymentID: 0a5480d8-3479-4f8d-ae4c-54a20fabee10
  Error: WARNING: Expected number of all hosts (0) to be remote +1 (0) (*errors.errorString)

go away, because of https://github.com/minio/minio/pull/10777

Change-Id: I9cad6a04659aeba0d12a01e8d3f6485adf5edc64