testsuite: Align dependencies for minio
This is necessary because of 1a458a6 and otherwise results in other
tools failing due to:

```
/go/pkg/mod/storj.io/gateway@v1.1.10-0.20201113230955-1a458a6bd098/miniogw/logging.go:35:9: cannot use &layerLogging literal (type *layerLogging) as type "github.com/minio/minio/cmd".ObjectLayer in return argument:
	*layerLogging does not implement "github.com/minio/minio/cmd".ObjectLayer (wrong type for NewNSLock method)
		have NewNSLock(string, ...string) "github.com/minio/minio/cmd".RWLocker
		want NewNSLock(context.Context, string, ...string) "github.com/minio/minio/cmd".RWLocker
/go/pkg/mod/storj.io/gateway@v1.1.10-0.20201113230955-1a458a6bd098/miniogw/logging.go:66:28: not enough arguments in call to log.layer.NewNSLock
	have (string, []string...)
	want (context.Context, string, ...string)
script returned exit code 2
```

Change-Id: Id8150cc57dc5372c5f7a337f3307898d3f3e381c